VERSION_MAJOR = 1
VERSION_MINOR = 0
VERSION_PATCH = 0
VERSION_STRING = \"1.0.0\"

DEFINES += BUMMERGRAM_VERSION_MAJOR=$$VERSION_MAJOR
DEFINES += BUMMERGRAM_VERSION_MINOR=$$VERSION_MINOR
DEFINES += BUMMERGRAM_VERSION_PATCH=$$VERSION_PATCH
DEFINES += BUMMERGRAM_VERSION_STRING=\\\"$$VERSION_STRING\\\"
