name: Build BummerGram (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Set up vcpkg
      shell: cmd
      run: |
        git clone https://github.com
        cd vcpkg
        call bootstrap-vcpkg.bat

    - name: Install Qt6 and Dependencies via vcpkg
      shell: cmd
      run: |
        vcpkg\vcpkg.exe install qtbase:x64-windows qt5compat:x64-windows

    - name: Configure and Build BummerGram
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake ..
        cmake --build . --config Release

    - name: Upload Finished EXE
      uses: actions/upload-artifact@v4
      with:
        name: BummerGram-Windows-x64
        path: build/bin/Release/BummerGram.exe
