name: Build BummerGram (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Install Pre-compiled Qt6
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.7.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'

    - name: Configure and Build BummerGram
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release

    - name: Upload Finished EXE
      uses: actions/upload-artifact@v4
      with:
        name: BummerGram-Windows-x64
        path: build/bin/Release/BummerGram.exe
